sudo: required
services:
  - docker

before_install:
  - docker build -t dustinvogel/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dustinvogel/multi-docker npm run test 

after_success:
  - docker build -t dustinvogel/multi-docker-client ./client
  - docker build -t dustinvogel/multi-docker-nginx ./nginx
  - docker build -t dustinvogel/multi-docker-server ./server
  - docker build -t dustinvogel/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dustinvogel/multi-docker-client
  - docker push dustinvogel/multi-docker-nginx
  - docker push dustinvogel/multi-docker-server
  - docker push dustinvogel/multi-docker-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: mdapp
  env: Mdapp-env
  bucket_name: elasticbeanstalk-us-west-2-707559742837
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


